on:
  push:
    branches:
      - main

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@main

          - uses: docker/setup-qemu-action@v3
      
          - uses: docker/setup-buildx-action@v3

          - uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - run: |
              docker buildx build --tag ghcr.io/emsro/build-env:latest --platform linux/amd64,linux/arm64 .
              docker push ghcr.io/emsro/build-env:latest

